== How to run the application ==

The application is started using maven wrapper.
To run the application ...

1) Start it up
On Windows: ./mvnw.cmd spring-boot:run
On Linux or MacOs ./mvnw spring-boot:run

2) Run the eval <bracket expression command> i.e. "eval y2[x]"
3) The output will be printed to the console i.e "yxx"
4) The log will indicate concrete error in case of incorrect input.

== How the application works ==

Application architecture

There are two classes which contain logic and algorithms.

1) Class "Expander" is responsible for expanding correctly recorded bracket expressions
   according to the task. All multipliers should be recorded only with square brackets.
   All square brackets have multipliers before them. Only Latin Letters are allowed. Zero can also be a multiplier.

2) Class "Validator" processes expression and gives a response about compliance with the task conditions.
   This class also displaces a Lombock log about type and place of mistake in bracket expression.

3) Tests cover all expression cases.

4) Input performs with Spring Shell command "eval".




